# Generated by Django 4.2.6 on 2023-10-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='detalle',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='comunicado',
            name='detalle_corto',
            field=models.TextField(max_length=100),
        ),
    ]
